# Generated by Django 5.2.7 on 2025-10-31 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0001_initial_models'),
    ]

    operations = [
    ]
