# Generated by Django 5.2.7 on 2025-11-04 16:39

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0002_populate_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['name'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.RemoveField(
            model_name='room',
            name='desk_total',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_image',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_name',
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(default='room101', help_text='Name of the room', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_desks',
            field=models.PositiveIntegerField(default=3, help_text='Total number of desks in this room', validators=[django.core.validators.MinValueValidator(1, message='Must have at least 1 desk'), django.core.validators.MaxValueValidator(100, message='Cannot exceed 100 desks')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='room',
            table=None,
        ),
    ]
