# Generated by Django 5.2.7 on 2025-11-06 20:21

import django.core.validators
import parcark.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0004_remove_booking_user_remove_image_room_delete_setting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, help_text='Room photo (max 2MB, JPG/PNG/WebP)', null=True, upload_to=parcark.models.room_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Only JPG, PNG, and WebP images are allowed.'), parcark.models.validate_image_size]),
        ),
    ]
