# Generated by Django 5.2.7 on 2025-11-08 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0005_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Desk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desk_number', models.PositiveIntegerField(help_text='Desk number within the room')),
                ('location_description', models.CharField(blank=True, help_text="e.g. 'Window side', 'Near door', 'Corner'", max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False to temporarily disable a desk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(help_text='Room this desk belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='desks', to='parcark.room')),
            ],
            options={
                'verbose_name': 'Desk',
                'verbose_name_plural': 'Desks',
                'ordering': ['room', 'desk_number'],
                'unique_together': {('room', 'desk_number')},
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of booking')),
                ('period', models.CharField(choices=[('am', 'Morning (AM)'), ('pm', 'Afternoon (PM)'), ('full', 'Full Day')], help_text='Time period for booking', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made the booking', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('desk', models.ForeignKey(help_text='Booked desk', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='parcark.desk')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['date', 'period'],
                'indexes': [models.Index(fields=['date', 'period'], name='parcark_boo_date_dc6514_idx'), models.Index(fields=['user', 'date'], name='parcark_boo_user_id_3155b6_idx')],
                'unique_together': {('desk', 'date', 'period')},
            },
        ),
    ]
