# Generated by Django 5.2.7 on 2025-11-20 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0006_desk_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='Enable LDAP authentication')),
                ('host', models.CharField(default='', help_text='LDAP server hostname', max_length=255)),
                ('port', models.PositiveIntegerField(default=389, help_text='LDAP port (389 for LDAP, 636 for LDAPS)')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use LDAPS (port 636)')),
                ('use_tls', models.BooleanField(default=False, help_text='Use STARTTLS')),
                ('version', models.PositiveIntegerField(choices=[(2, 'v2'), (3, 'v3')], default=3, help_text='LDAP protocol version')),
                ('timeout', models.PositiveIntegerField(default=5, help_text='Connection timeout in seconds')),
                ('bind_dn', models.CharField(blank=True, default='', help_text='Service account DN', max_length=255)),
                ('bind_password', models.CharField(blank=True, default='', help_text='Service account password', max_length=255)),
                ('base_dn', models.CharField(default='', help_text='Base DN for searches', max_length=255)),
                ('user_search_dn', models.CharField(default='', help_text='DN to search for users', max_length=255)),
                ('user_search_filter', models.CharField(default='(sAMAccountName=%(user)s)', help_text='Search filter (use %(user)s)', max_length=255)),
                ('attr_map_username', models.CharField(default='sAMAccountName', help_text='Username attribute', max_length=50)),
                ('attr_map_first_name', models.CharField(default='givenName', help_text='First name attribute', max_length=50)),
                ('attr_map_last_name', models.CharField(default='sn', help_text='Last name attribute', max_length=50)),
                ('attr_map_email', models.CharField(default='mail', help_text='Email attribute', max_length=50)),
                ('cert_file_path', models.CharField(blank=True, default='/app/ldap-cert-chain.crt', help_text='Path to cert file', max_length=500)),
                ('cert_require', models.CharField(choices=[('never', 'Never (no validation)'), ('allow', 'Allow (try validation)'), ('demand', 'Demand (strict)')], default='never', help_text='Certificate validation level', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ldap_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LDAP Settings',
                'verbose_name_plural': 'LDAP Settings',
            },
        ),
    ]
