# Generated by Django 5.2.7 on 2025-11-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0007_ldapsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='bind_password_encrypted',
            field=models.BinaryField(blank=True),
        ),
    ]
