# Generated by Django 5.2.7 on 2025-11-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0008_ldapsettings_bind_password_encrypted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapsettings',
            name='bind_password_encrypted',
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='bind_password',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
