# Generated by Django 5.2.7 on 2026-02-14 09:47

import django.db.models.deletion
import parcark.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0009_remove_ldapsettings_bind_password_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('canvas_width', models.PositiveIntegerField(default=1200)),
                ('canvas_height', models.PositiveIntegerField(default=800)),
                ('layout_json', models.JSONField(default=parcark.models.default_room_layout_json)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='layout', to='parcark.room')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_layout_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Room Layout',
                'verbose_name_plural': 'Room Layouts',
            },
        ),
    ]
