# Generated by Django 5.2.7 on 2026-02-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcark', '0010_roomlayout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomlayout',
            name='canvas_width',
            field=models.PositiveIntegerField(default=800),
        ),
    ]
